Repository FC-DEV2-FinalProject/Charmander_FE, pull requests merged in 2025-03, with the labels that each got.

#3 feat: 프로젝트 생성 페이지 사이드바 레이아웃 제작
  src/assets/projectIcon/article.svg
  src/assets/projectIcon/avatar.svg
  src/assets/projectIcon/chooseTemplate.svg
  src/assets/projectIcon/edit-2.svg
  src/assets/projectIcon/gallery.svg
  src/assets/projectIcon/script.svg
  src/routeTree.gen.ts
  src/routes/_projectSideBarLayout.tsx
  src/routes/_projectSideBarLayout/$project/article/index.tsx
  src/routes/_projectSideBarLayout/$project/avatar/index.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/script/index.tsx
  src/routes/_projectSideBarLayout/$project/template/index.tsx
Labels: feat

#9 feat: 프로젝트 생성 페이지 헤더 제작 (#7)
  src/components/project-editor/header/index.tsx
  src/routeTree.gen.ts
  src/routes/_projectSideBarLayout.tsx
Labels: feat

#6 Feat/sidebar
  src/assets/icons/icon-dashboard.svg
  src/assets/icons/icon-headphone.svg
  src/assets/icons/icon-my-project.svg
  src/assets/icons/icon-plus.svg
  src/assets/icons/icon-right-arrow.svg
  src/assets/icons/icon-up-and-down.svg
  src/assets/icons/icon-video-archive.svg
  src/assets/images/logo.svg
  src/components/SideBarUserModal.tsx
  src/components/icons/DashboardIcon.tsx
  src/components/icons/MyProjectIcon.tsx
  src/components/icons/VideoArchiveIcon.tsx
  src/routes/_sideBarLayout.tsx
  src/store/useDialogStore.ts
  src/styles/theme.ts
Labels: feat, asset, design

#13 feat: figma에 정의된 회원가입 절차 컴포넌트를 구현합니다 (#8)
  src/components/auth/sign-in/agreement/index.tsx
  src/components/auth/sign-in/info/index.tsx
  src/components/auth/sign-in/password/index.tsx
  src/components/auth/sign-in/phone/index.tsx
  src/routes/auth/sign-in/index.tsx
  src/schema/SignUpSchema.ts
  src/utils/validation.ts
Labels: feat, refactor

#11 feat: 마이 페이지 UI 퍼블리싱 (#10)
  src/components/common/imageUpload/index.tsx
  src/routeTree.gen.ts
  src/routes/_sideBarLayout/my-page/index.tsx
Labels: feat

#16 refactor: 눈 아이콘 변경 (#15)
  src/components/common/input/index.tsx
Labels: refactor

#12 feat: 프로젝트 생성 페이지 - 기사 입력 페이지 구현 (#4)
  package-lock.json
  package.json
  src/assets/projectIcon/back.svg
  src/components/project-editor/header/index.tsx
  src/hook/useDebounce.ts
  src/routeTree.gen.ts
  src/routes/_projectSideBarLayout/$project/article/index.tsx
  src/store/useArticlePDFStore.ts
  src/styles/theme.ts
Labels: feat

#18 feat: 템플릿 선택 페이지 퍼블리싱 (#4)
  src/components/common/dropdown/index.tsx
  src/components/project-editor/header/index.tsx
  src/routes/_projectSideBarLayout.tsx
  src/routes/_projectSideBarLayout/$project/template/index.tsx
  src/types/commonUi.ts
Labels: feat

#19 feat: 프로젝트 배경 페이지 퍼블리싱
  src/assets/projectIcon/Frame.svg
  src/assets/projectIcon/background-sidebarIcon.svg
  src/assets/projectIcon/backgroundFileUploadIcon.svg
  src/assets/projectIcon/deleteBackground.svg
  src/assets/projectIcon/generateBackground.svg
  src/assets/projectIcon/imageUploadIcon.svg
  src/components/project-editor/dragImage/index.tsx
  src/mock/mockTemplateImage.ts
  src/routes/_projectSideBarLayout.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/template/index.tsx
Labels: feat

#21 feat: youtube 모달 생성 (#17)
  src/api/login/oAuth-config.ts
  src/api/login/oauth-service.ts
  src/assets/images/image.png
  src/components/auth/sign-in/agreement/index.tsx
  src/components/common/modal/tosModal/index.tsx
  src/routes/auth/sign-in/index.tsx
Labels: feat

#25 refactor: 카카오 구글 로그인 getToken 제거 (#24)
  src/api/login/oauth-service.ts
  src/routes/auth/callback/google/index.tsx
  src/routes/auth/callback/kakao/index.tsx
Labels: refactor

#28 feat: access Token과 refresh 토큰 전역관리 (#26)
  src/routes/auth/sign-in/index.tsx
  src/store/store.ts
  src/utils/getTokens.ts
Labels: feat

#33 feat: 아바타 선택 페이지 퍼블리싱
  src/components/common/dropdown/index.tsx
  src/components/project-editor/dragImage/index.tsx
  src/routes/_projectSideBarLayout/$project/avatar/index.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/template/index.tsx
  src/store/useAspectRatioStore.ts
  src/types/commonUi.ts
Labels: feat

#35 refactor: 백엔드분들의 의견 반영 (#34)
  public/mockServiceWorker.js
  src/api/login/oAuth-config.ts
  src/components/googleLoginButton/index.tsx
  src/components/kakaoLoginButton/index.tsx
  src/routes/auth/callback/google/index.tsx
  src/routes/auth/callback/kakao/index.tsx
  src/routes/auth/sign-up/sns/index.tsx
Labels: refactor

#37 refactor: figma에 정의된대로 css 속성들을 수정합니다 (#36)
  src/assets/auth/key-01.svg
  src/assets/auth/sms.svg
  src/components/auth/sign-in/agreement/index.tsx
  src/components/common/bannerSlider/index.tsx
  src/components/common/input/index.tsx
  src/components/googleLoginButton/index.tsx
  src/routes/_sideBarLayout/my-page/index.tsx
  src/routes/auth/login/index.tsx
  src/routes/auth/sign-in/index.tsx
  src/styles/theme.ts
Labels: refactor

#41 refactor: api 함수를 수정합니다 (#38)
  src/api/login/api.ts
  vite.config.ts
Labels: refactor

#42 feat: 프로젝트 대사/자막 입력 페이지 퍼블리싱(#4)
  src/assets/projectIcon/article-white.svg
  src/assets/projectIcon/article.svg
  src/assets/projectIcon/avatar.svg
  src/assets/projectIcon/background-white.svg
  src/assets/projectIcon/background.svg
  src/assets/projectIcon/chooseTemplate.svg
  src/assets/projectIcon/deleteIcon.svg
  src/assets/projectIcon/emoji-happy-white.svg
  src/assets/projectIcon/emoji-happy.svg
  src/assets/projectIcon/gallery.svg
  src/assets/projectIcon/script-white.svg
  src/assets/projectIcon/script.svg
  src/assets/projectIcon/scriptTemplateLong.svg
  src/assets/projectIcon/scriptTemplateShort.svg
  src/assets/projectIcon/template-white.svg
  src/assets/projectIcon/template.svg
  src/assets/projectIcon/transparentBackground.svg
  src/components/common/dropdown/index.tsx
  src/components/project-editor/scriptSection/index.tsx
  src/components/project-editor/scriptTermInput/index.tsx
  src/routes/_projectSideBarLayout.tsx
  src/routes/_projectSideBarLayout/$project/avatar/index.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/script/index.tsx
  src/types/subtitle.ts
Labels: feat

#44 feat: 제작하기 모달 및 경고 모달 퍼블리싱 (#43)
  src/assets/projectIcon/alert-triangle.svg
  src/assets/projectIcon/free-icon-video-production.svg
  src/assets/projectIcon/icon_size.svg
  src/components/common/modal/index.tsx
  src/components/project-editor/header/index.tsx
  src/components/project-editor/modal/editModal.tsx
  src/components/project-editor/modal/warningModal.tsx
Labels: feat

#46 refactor: vite.config.ts 파일을 수정 (#45)
  src/api/login/oAuth-config.ts
  src/api/sign-up/api.ts
  src/assets/arrow_drop_up.svg
  src/assets/projectIcon/article.svg
  src/assets/projectIcon/avatar.svg
  src/assets/projectIcon/chooseTemplate.svg
  src/assets/projectIcon/gallery.svg
  src/assets/projectIcon/script.svg
  src/components/SideBarUserModal.tsx
  src/components/common/bannerSlider/index.tsx
  src/components/common/dropdown/index.tsx
  src/mock/dummy.json
  src/routeTree.gen.ts
  src/routes/__root.tsx
  src/routes/_projectSideBarLayout.tsx
  src/routes/_projectSideBarLayout/$project/avatar/index.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/script/index.tsx
  src/routes/_sideBarLayout.tsx
  src/routes/_sideBarLayout/dashboard/_components/chart.tsx
  src/routes/_sideBarLayout/dashboard/_components/guide.tsx
  src/routes/_sideBarLayout/dashboard/_components/myProjectCard.tsx
  src/routes/_sideBarLayout/dashboard/index.tsx
  src/routes/_sideBarLayout/my-project/index.tsx
  src/routes/auth/callback/google/index.tsx
  src/routes/auth/callback/kakao/index.tsx
  src/routes/auth/sign-up/sns/index.tsx
  src/utils/auth.ts
  vite.config.ts
Labels: refactor

#56 feat: msw 설정 (#55)
  src/api/project/api.ts
  src/components/project-editor/header/index.tsx
  src/main.tsx
  src/mock/browser.ts
  src/mock/dummy.json
  src/mock/handlers.ts
Labels: feat

#58 feat: 로그인 사용자 정보 출력 (#47)
  src/api/myPage/api.ts
  src/routes/_sideBarLayout/my-page/index.tsx
Labels: feat

#64 refactor: 사용자 정보 출력 데이터 수정 (#62)
  src/routes/_sideBarLayout/my-page/index.tsx
Labels: refactor

#59 feat: sns 회원가입 및 로그인 기능 구현 (#48)
  src/api/login/oAuth-config.ts
  src/routes/auth/callback/google/index.tsx
  src/routes/auth/callback/kakao/index.tsx
Labels: feat

#68 refactor: 사이드바 데이터 연동 및 api 적용 (#67)
  src/api/dashboard/api.ts
  src/components/SideBarUserModal.tsx
  src/routes/_sideBarLayout.tsx
  src/utils/Tokens.ts
Labels: refactor

#70 refactor: 마이페이지 아이콘 변경 (#69)
  src/components/common/imageUpload/index.tsx
  src/routes/_sideBarLayout/my-page/index.tsx
Labels: refactor

#74 feat: 대시보드와 내 프로젝트, 영상보관함 api 연동 (#73)
  src/api/dashboard/api.ts
  src/api/video-archive/api.ts
  src/main.tsx
  src/routes/_sideBarLayout/dashboard/_components/myProjectCard.tsx
  src/routes/_sideBarLayout/dashboard/index.tsx
  src/routes/_sideBarLayout/my-project/_components/projectCard.tsx
  src/routes/_sideBarLayout/my-project/index.tsx
  src/routes/_sideBarLayout/video-archive/index.tsx
  src/utils/sort.ts
Labels: feat

#76 fix: 프로젝트 header 타입 오류 수정(#75)
  src/components/project-editor/header/index.tsx
Labels: fix

#79 refactor: 대시보드 프로젝트 상세 보기 경로 수정 (#78)
  src/routes/_sideBarLayout/dashboard/_components/myProjectCard.tsx
Labels: refactor

#81 refactor: 내 프로젝트 삭제 api 경로 수정 (#80)
  src/api/dashboard/api.ts
Labels: refactor

#83 feat: 로그인 페이지 엔터 로그인(#82)
  src/routes/auth/login/index.tsx
Labels: feat

#85 feat: redirect url state를 추출 api 요청 (#84)
  src/api/login/oauth-service.ts
  src/routes/auth/callback/google/index.tsx
  src/routes/auth/callback/kakao/index.tsx
Labels: feat

#86 feat: 배경 선택 페이지 api 연결(#72)
  package-lock.json
  package.json
  src/api/project/api.ts
  src/components/project-editor/dragImage/index.tsx
  src/components/project-editor/header/index.tsx
  src/hook/useTemplateList.ts
  src/main.tsx
  src/mock/templateImage.json
  src/routes/_projectSideBarLayout.tsx
  src/routes/_projectSideBarLayout/$project/article/index.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/template/index.tsx
  src/store/useProjectEditorStore.ts
  src/types/projectData.ts
  src/types/template.ts
Labels: feat

#87 feat: 아바타 선택 페이지 api 1차 작업(#72)
  src/api/project/api.ts
  src/routes/_projectSideBarLayout/$project/avatar/index.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/template/index.tsx
  src/store/useProjectEditorStore.ts
  src/types/projectData.ts
Labels: feat

#90 feat: 내 프로젝트 페이지 무한 스크롤 적용 (#89)
  package-lock.json
  package.json
  src/api/dashboard/api.ts
  src/components/loading/LoadingSpinner.tsx
  src/routes/_sideBarLayout/my-project/index.tsx
Labels: feat

#92 feat: 대사 입력 페이지 api작업 #88
  src/api/project/api.ts
  src/components/project-editor/dragImage/index.tsx
  src/components/project-editor/header/index.tsx
  src/components/project-editor/modal/editModal.tsx
  src/components/project-editor/scriptSection/index.tsx
  src/components/project-editor/scriptTermInput/index.tsx
  src/mock/projectDummy.json
  src/mock/templateImage.json
  src/routes/_projectSideBarLayout/$project/avatar/index.tsx
  src/routes/_projectSideBarLayout/$project/background/index.tsx
  src/routes/_projectSideBarLayout/$project/script/index.tsx
  src/routes/_projectSideBarLayout/$project/template/index.tsx
  src/store/useProjectEditorStore.ts
  src/types/projectData.ts
  src/types/subtitle.ts
Labels: feat
